# Generated by Django 4.2.2 on 2023-11-01 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=2, null=True)),
                ('lot', models.CharField(blank=True, max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_type_client', to='configuration.clienttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_client', to='configuration.person')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'permissions': (('view_client', 'Listar Clientes'), ('add_client', 'Agregar Clientes'), ('update_client', 'Actualizar Clientes'), ('delete_client', 'Eliminar Clientes')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('serie_payment', models.CharField(max_length=4)),
                ('nro_payment', models.CharField(max_length=20)),
                ('nro_operation', models.CharField(max_length=20)),
                ('file_operation', models.ImageField(blank=True, null=True, upload_to='operation/payment')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_payment', to='operation.client')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_payment', to='configuration.paymentmethod')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'permissions': (('view_payment', 'Listar Pagos'), ('add_payment', 'Agregar Pagos'), ('update_payment', 'Actualizar Pagos'), ('delete_payment', 'Eliminar Pagos')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'permissions': (('view_service', 'Listar Servicios'), ('add_service', 'Agregar Servicios'), ('update_service', 'Actualizar Servicios'), ('delete_service', 'Eliminar Servicios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('extension_days', models.DecimalField(decimal_places=0, default=5, max_digits=18)),
                ('reconnection_cost', models.DecimalField(decimal_places=2, default=5, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_type_plan', to='configuration.clienttype')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'permissions': (('view_plan', 'Listar Planes'), ('add_plan', 'Agregar Planes'), ('update_plan', 'Actualizar Planes'), ('delete_plan', 'Eliminar Planes')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_payment_detail', to='operation.payment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_payment_detail', to='operation.service')),
            ],
            options={
                'verbose_name': 'Pago detalle',
                'verbose_name_plural': 'Pago detalles',
                'permissions': (('view_paymentdetail', 'Listar Pago detalles'), ('add_paymentdetail', 'Agregar Pago detalles'), ('update_paymentdetail', 'Actualizar Pago detalles'), ('delete_paymentdetail', 'Eliminar Pago detalles')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_payment', to='operation.plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_client', to='operation.plan'),
        ),
        migrations.AddField(
            model_name='client',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='situation_client', to='configuration.situation'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
