# Generated by Django 4.2.2 on 2023-11-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='retired_extension_days',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=18),
        ),
    ]
