# Generated by Django 4.2.2 on 2023-11-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_client_is_retired_plan_retired_extension_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='extension_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reconnection_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='plan',
            name='retired_extension_days',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True),
        ),
    ]
