# Generated by Django 4.2.2 on 2023-11-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_plan_extension_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_finalized_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='gloss',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_payment_detail', to='operation.service'),
        ),
    ]
