# Generated by Django 4.2.2 on 2023-11-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_payment_nro_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
