# Generated by Django 4.2.2 on 2023-11-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
