# Generated by Django 4.2.2 on 2023-11-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_plan_reconnection_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_quota', to='operation.client')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_quota', to='operation.plan')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'permissions': (('view_quota', 'Listar Cuotas'), ('add_quota', 'Agregar Cuotas'), ('update_quota', 'Actualizar Cuotas'), ('delete_quota', 'Eliminar Cuotas')),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.CreateModel(
            name='QuotaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gloss', models.CharField(max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_quota_detail', to='operation.quota')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_quota_detail', to='operation.service')),
            ],
            options={
                'verbose_name': 'Cuota detalle',
                'verbose_name_plural': 'Cuota detalles',
                'permissions': (('view_quotadetail', 'Listar Cuota detalles'), ('add_quotadetail', 'Agregar Cuota detalles'), ('update_quotadetail', 'Actualizar Cuota detalles'), ('delete_quotadetail', 'Eliminar Cuota detalles')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quota_payment', to='operation.quota'),
        ),
    ]
