# Generated by Django 4.2.2 on 2023-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_quota_remove_payment_month_remove_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_finalized_contract',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_retired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
