# Generated by Django 4.2.2 on 2023-11-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_quota_year_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_finalized_contract',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.DateTimeField(default='2023-11-01'),
            preserve_default=False,
        ),
    ]
