# Generated by Django 4.2.2 on 2023-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_date_finalized_contract_client_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotadetail',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
